# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/apps/Bingo.Caller.App"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/apps/Bingo.Player.App"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.AppServices"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.Core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.ImageProcessing"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.Infrastructure"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.Integrations"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.Services"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.UI.Shared"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/libs/Bingo.ViewModel"
    schedule:
      interval: "weekly"
