<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interface\**" />
    <Compile Remove="Repository\**" />
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Interface\**" />
    <EmbeddedResource Remove="Repository\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Interface\**" />
    <None Remove="Repository\**" />
    <None Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="BoardRules\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
