<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\patterns.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\patterns.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bingo.Core\Bingo.Core.csproj" />
    <ProjectReference Include="..\Bingo.Services\Bingo.Services.csproj" />
  </ItemGroup>

</Project>
